[package]
name = "adblock-coffee"
version = "0.1.3"
edition = "2021"
authors = ["Bread White <breadrock1@gmail.com>"]

[lib]
crate_type = ["cdylib"]

[dependencies]
anyhow = "^1.0"
adblock = "^0.8"
jni = "^0.21"
thiserror = "^1.0"
log = "0.4.22"
