name: "Build project"
on:
  pull_request:

jobs:
  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

  build:
    name: build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build rust library
        run: |
          cargo build --manifest-path adblock-rs/Cargo.toml
          mkdir -p ./target/lib
          cp -r ./adblock-rs/target/release/libadblock_coffee.* ./target/lib/
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      - name: Build java library
        run: mvn package

  cargo-test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build rust library
        run: cargo test --all

  mvn-test:
    name: mvn test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build rust library
        run: |
          cargo build --manifest-path adblock-rs/Cargo.toml
          mkdir -p ./target/lib
          cp -r ./adblock-rs/target/release/libadblock_coffee.* ./target/lib/
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      - name: Run test by maven
        run: mvn test
