name: "Build project"
on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  build:
    name: build project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-target: [
          'x86_64-unknown-linux-gnu'
        ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.rust-toolchain }}
      - name: Build rust library for ${{ matrix.rust-toolchain }}
        run: |
          cargo build
          cp -r adblock-rs/target/debug/libadblock_coffee.* .
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      - name: Build java library
        run: mvn package
